### PR TITLE
Fix notification logging.

### LINKED ISSUE #244: Event action 'app-launch-from-notification' is not recorded for iOS
This is happening in both dev and market version. The information about launching the app from the notification is not being recorded.

### PR DESCRIPTION
**Pull request by arcturus**
Closes #244

### CODE REVIEW

**Comment by arcturus** [comment]
@wilsonpage r?

We had a stupid comparison, that's valid just when the app is not running, but we want to notify no matter what's app status.

**Comment by wilsonpage** [comment]
Nice catch :)

Unrelated: Ideally we shouldn't be writing code in `AppDelegate.m` as this is really RN territory. Would be better if we can move all out code into separate modules. in Android we have to much code in `MainActivity.java`, that too needs moving. Not urgent, just a thought.

**Comment by wilsonpage** [comment]
Shiiiiip it +r

**Comment by arcturus** [comment]
Definitely a good practice, but we will let the refactors for post-gate1? ;)

**Pull request merged**
