### PR TITLE
Implemented expanded view (closes #85)

### LINKED ISSUE #85: Implement 'expanded' view
We need a visual for what the expanded/detail view of the tile looks like.

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by wilsonpage** [comment]
@samgiles some more tweaks needed, but ready for an initial f?

Still to do: 
- [x] Check on iOS
- [x] Fix touches not working properly on webview content
- [x] Unit-tests

**Comment by samgiles** [comment]
lgtm so far.  Do we need `var`s everywhere though?  Pretty sure a `const` will do in most cases here.

**Comment by wilsonpage** [comment]
Just waiting on green. If we want to swap all `var` for `const` then we should do that in a separate issue as it's unrelated to this patch. Although I'm still not convinced it brings much value. Just seems like more chars to write IMO.

**Comment by arcturus** [comment]
+1 to use const when makes sense ;) (sorry @wilsonpage )

**Comment by wilsonpage** [comment]
@arcturus followup #120

**Pull request merged**
