### PR TITLE
Add some missing telemetry (closes #374)

### LINKED ISSUE #374: Telemetry - Event item-populated is not recorded in GA
This was seen before but is not recorded in latest builds

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by wilsonpage** [comment]
@arcturus r? @isabelrios

**Comment by isabelrios** [comment]
@wilsonpage sorry but cannot see the items: item-fetched, channel-subscribed and channel-unsubscribed

**Comment by wilsonpage** [comment]
@isabelrios this hasn't landed yet, did you test with this branch?

**Comment by isabelrios** [comment]
@wilsonpage yes, I tried with this branch

**Comment by wilsonpage** [comment]
@isabelrios this branch hasn't been rebased to include the telemetry fixes Sam added on Friday, could that be the issue?

**Comment by isabelrios** [comment]
@wilsonpage I saw the other events with the workaround (turning telemetry setting off/on) but could not see the events in this patch. I will check again and also will try to rebase master and try again.

**Comment by isabelrios** [comment]
@wilsonpage good news I just tested again this branch, and now I can see all the events:
item-fetched, channel-subscribed and channel-unsubscribed.
I do not know what was the problem but seems that the events are correctly recorded.

**Review by samgiles — APPROVED** [review]
Looks good to me! r=me

**Pull request merged**
