### PR TITLE
Remove bad Activity

### PR DESCRIPTION
**Pull request by samgiles**
@wilsonpage This was causing #81, not sure why it was needed if at all.

### CODE REVIEW

**Comment by wilsonpage** [comment]
@samgiles ah, I think this was introduced by the recent `react-native upgrade`. I've removed this file once before, keeps finding its way back!

**Comment by wilsonpage** [comment]
Let's wait till green and land?

**Comment by wilsonpage** [comment]
@samgiles now we're getting that timeout:

```
No output has been received in the last 10m0s, this potentially
indicates a stalled build or something wrong with the build itself.
```

**Comment by samgiles** [comment]
Let's merge this, the push check passed with Travis and no-one can really build off of a broken master.

**Pull request merged**
